site_name: PyCloudWorld
site_url: https://pycloudworld.github.io/webpages/
nav:
    - Home: index.md
    - About: about.md
    - Learning: 
        Azure: 
            Compute Resources:
                Azure Containers: learning/azure/compute_resources/azure_containers.md
            Virtual Networking:
                Network Interface & CIDR Notation: learning/azure/virtual_networking/network_interface_n_cidr_notation.md
                Virtual Network: learning/azure/virtual_networking/virtual_network.md
                Network Security Group: learning/azure/virtual_networking/network_security_group.md
                Application Security Group: learning/azure/virtual_networking/application_security_group.md
                Site to Site VPN Connection: learning/azure/virtual_networking/site-to-site.md
                Virtual WAN: learning/azure/virtual_networking/virtual_WAN.md
                ExpressRoute: learning/azure/virtual_networking/express_route.md
                User Defined Routes: learning/azure/virtual_networking/user_defined_routes.md
                Azure Firewall Service: learning/azure/virtual_networking/azure_firewall_service.md
            Azure Storage:
                What are storage accounts: learning/azure/azure_storage/what_are_storage_accounts.md
            Azure Manage Identities And Governance(44 lectures):
                azure_subscriptions: learning/azure/manage_azure_identities_and_governance/azure_subscriptions.md
                custom_ad_roles: learning/azure/manage_azure_identities_and_governance/custom_ad_roles.md
                VM_RBAC_rules: learning/azure/manage_azure_identities_and_governance/VM_RBAC_rules.md
                add_vm_to_ad: learning/azure/manage_azure_identities_and_governance/add_vm_to_ad.md
                azure_ad_custom_domains: learning/azure/manage_azure_identities_and_governance/azure_ad_custom_domains.md
                assigning_azure_ad_roles: learning/azure/manage_azure_identities_and_governance/assigning_azure_ad_roles.md
                dynamic_group: learning/azure/manage_azure_identities_and_governance/dynamic_group.md
                storage_account_role: learning/azure/manage_azure_identities_and_governance/storage_account_role.md
            Monitor and Backup Resources:
                1 what_is_monitoring : learning/azure/monitor_and_backup_resources/1_what_is_monitoring.md
                2 quick_look_at_azure_monitoring : learning/azure/monitor_and_backup_resources/2_quick_look_at_azure_monitoring.md
                3 alerts : learning/azure/monitor_and_backup_resources/3_alerts.md
    - Programming:
        Design Patterns:
            Creational Design Patterns:
                Singleton: programming/design_patterns/creational_patterns/singleton.md
                Builder: programming/design_patterns/creational_patterns/builder.md
                Factory Method: programming/design_patterns/creational_patterns/factory_method.md
                Prototype: programming/design_patterns/creational_patterns/prototype.md
                Abstract Factory: programming/design_patterns/creational_patterns/abstract_factory.md
            Structural Patterns:
                Adapter: programming/design_patterns/structural_patterns/adapter.md
                Proxy: programming/design_patterns/structural_patterns/proxy.md

