site_name: PyCloudWorld
site_url: https://pycloudworld.github.io/webpages/
nav:
    - Home: index.md
    - About: about.md
    - Learning: 
        Azure: 
            Compute Resources:
                Azure Containers: learning/azure/compute_resources/azure_containers.md
            Virtual Networking:
                Network Interface & CIDR Notation: learning/azure/virtual_networking/network_interface_n_cidr_notation.md
                Virtual Network: learning/azure/virtual_networking/virtual_network.md
                Network Security Group: learning/azure/virtual_networking/network_security_group.md
    - Programming:
        Design Patterns:
            Creational Design Patterns:
                Singleton: programming/design_patterns/creational_patterns/singleton.md
                Builder: programming/design_patterns/creational_patterns/builder.md
                Factory Method: programming/design_patterns/creational_patterns/factory_method.md
            Structural Patterns:
                Proxy: programming/design_patterns/structural_patterns/proxy.md

