site_name: PyCloudWorld
site_url: https://pycloudworld.github.io/webpages/
nav:
    - Home: index.md
    - About: about.md
    - Learning: 
        Azure: 
            Compute Resources:
                Azure Containers: learning/azure/compute_resources/azure_containers.md
            Virtual Networking:
                  CIDR Notation: learning/azure/virtual_networking/cidr_notation.md
    - Programming:
        Design Patterns:
            Creational Design Patterns:
                Singleton: programming/design_patterns/creational_design_patterns/singleton.md
                Builder: programming/design_patterns/creational_design_patterns/builder.md
            Structural Patterns:
                Proxy: programming/design_patterns/structural_patterns/proxy.md

